language: node_js

node_js:
  - '8'
  - '10'

dist: trusty

install:
  - npm ci 

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: npm release
      node_js: "10"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: dannydainton@gmail.com
        api_key: $NPM_TOKEN
        on: deploy-npm-release


  
