name: npm-publish
on:
  push:
    branches:
      - master
jobs:
    build:
      name: Build and Test
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        
      - name: Install and run tests
        run: |
          npm ci
  
    npm-publish:
      needs: [build]
      name: Publish package to NPM
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Check for a new version change
        uses: EndBug/version-check@v1
        id: check
        
      - name: No version update detected
        if: steps.check.outputs.changed != 'true'
        run: 'echo "Version not changed!"'

      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }}"'

      - name: Set up Node.js for NPM
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Publish package to NPM
        if: steps.check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
